# -*- coding: utf-8 -*-
"""Bake the US map into static/js/us-map.js: the projection runs ONCE, at build time.

    python gen_us_map.py

The runtime then only fills paths - no geometry maths, no projection library, no
dependency and no network call. Source data is `usa.topo.json` beside this script,
from kristw/gridmap-layout-usa (MIT), itself Census TIGER-derived; it is committed
(against the *.json ignore rule, deliberately) so the build works from a clean
checkout. Re-run only when the boundaries or the inset boxes need to change.

Two traps, both of which bit on the way in and are handled below:
  * Albers increases NORTHWARD and SVG increases downward, so the map renders upside
    down without the flip - and it looks plausible enough at a glance to ship.
  * Alaska's Aleutians cross the antimeridian, so its raw bounding box spans nearly
    the globe and the mainland fits to a speck without the unwrap.
"""
import io, json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "static", "js", "us-map.js")

topo = json.load(io.open(os.path.join(HERE, "usa.topo.json"), encoding="utf-8"))
scale, translate = topo["transform"]["scale"], topo["transform"]["translate"]


def decode(arc):
    x = y = 0
    out = []
    for dx, dy in arc:
        x += dx; y += dy
        out.append((x * scale[0] + translate[0], y * scale[1] + translate[1]))
    return out


ARCS = [decode(a) for a in topo["arcs"]]


def ring(idxs):
    pts = []
    for i in idxs:
        a = ARCS[~i][::-1] if i < 0 else ARCS[i]
        pts.extend(a[1:] if pts else a)
    return pts


def albers(lon, lat, lon0=-96.0, p1=29.5, p2=45.5, lat0=37.5):
    """Albers equal-area conic, the standard US projection. The y is NEGATED because
    Albers increases northward and SVG increases downward — without it the map renders
    upside down, which looks plausible enough at a glance to ship by accident."""
    r = math.radians
    n = (math.sin(r(p1)) + math.sin(r(p2))) / 2
    C = math.cos(r(p1)) ** 2 + 2 * n * math.sin(r(p1))
    rho = math.sqrt(C - 2 * n * math.sin(r(lat))) / n
    rho0 = math.sqrt(C - 2 * n * math.sin(r(lat0))) / n
    th = n * r(lon - lon0)
    return rho * math.sin(th), -(rho0 - rho * math.cos(th))


def unwrap(name, lon, lat):
    """Alaska's Aleutians cross the antimeridian, so its raw longitudes run from -179
    to +179 and its bounding box spans nearly the globe — fit it and the mainland
    collapses to a speck, which is exactly what the first cut did. Bringing the
    positive lobe round by 360 makes the state contiguous in -190..-130."""
    if name == "Alaska" and lon > 0:
        lon -= 360
    return albers(lon, lat)


geoms = {}
for g in topo["objects"]["units"]["geometries"]:
    nm = g["properties"]["name"]
    polys = g["arcs"] if g["type"] == "MultiPolygon" else [g["arcs"]]
    geoms[nm] = [[unwrap(nm, *p) for p in ring(r)] for poly in polys for r in poly]

W, H = 520, 316
L48 = [n for n in geoms if n not in ("Alaska", "Hawaii", "Puerto Rico")]


def bounds(names):
    pts = [p for n in names for r in geoms[n] for p in r]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)


def emit(names, box, min_px=0.6):
    """Project `names` into `box` (x, y, w, h), dropping shapes below min_px so a few
    dozen offshore islands don't cost more path length than the mainland."""
    bx, by, bw, bh = box
    x0, y0, x1, y1 = bounds(names)
    k = min(bw / (x1 - x0), bh / (y1 - y0))
    ox = bx + (bw - (x1 - x0) * k) / 2
    oy = by + (bh - (y1 - y0) * k) / 2
    out = {}
    for n in names:
        d = []
        for r in geoms[n]:
            xs = [p[0] for p in r]; ys = [p[1] for p in r]
            if (max(xs) - min(xs)) * k < min_px and (max(ys) - min(ys)) * k < min_px:
                continue
            d.append("M" + "L".join(f"{(p[0]-x0)*k+ox:.1f},{(p[1]-y0)*k+oy:.1f}"
                                   for p in r) + "Z")
        if d:
            out[n] = "".join(d)
    return out

# Alaska gets a real box, not a footnote: it is a fifth of the land area of the
# lower 48 and at the first cut it rendered as a speck (user, 2026-08-29).
paths = emit(L48, (2, 2, W - 4, H - 74))
paths.update(emit(["Alaska"], (6, H - 104, 132, 96)))
paths.update(emit(["Hawaii"], (150, H - 56, 62, 40)))

js = ("// GENERATED by scratchpad/gen_us_map.py — do not hand-edit.\n"
      "// US state outlines, Albers equal-area conic, pre-projected at build time so the\n"
      "// panel only has to fill them. Alaska and Hawaii are inset bottom-left at their\n"
      "// own scales. Source: kristw/gridmap-layout-usa usa.topo.json (MIT), Census\n"
      "// TIGER-derived. Keyed by full state name, which is what the regulatory roster\n"
      "// carries.\n"
      f"const US_MAP = {{ w: {W}, h: {H}, paths: "
      + json.dumps(paths, separators=(",", ":"), sort_keys=True) + " };\n")
io.open(OUT, "w", encoding="utf-8").write(js)
print(f"wrote {OUT}: {len(js)/1024:.1f} KB, {len(paths)} shapes")
